[package]
name = "inform"
description = "Another rust indentation formatter"
version = "0.3.1"
edition = "2021"
authors = ["Ethan Uppal"]
repository = "https://github.com/ethanuppal/inform"
license = "LGPL-3.0-or-later"

[features]
default = ["fmt", "io"]
fmt = []
io = []

[dependencies]
